import React from 'react';
import { motion } from 'framer-motion';

const fadeInUp = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: "easeOut" } }
};

const PrivacyPolicyPage = () => {
    return (
        <div className="min-h-screen bg-[#0F0F13] text-[#F5F5F7] font-sans selection:bg-[#D88A3D]/30 w-full overflow-x-hidden pt-24 md:pt-32">
            <div className="max-w-[800px] mx-auto px-5 md:px-8 pb-[70px] md:pb-[90px] lg:pb-[120px] text-left">
                
                {/* SECTION 1 — TITLE */}
                <motion.section 
                    initial="hidden"
                    animate="visible"
                    variants={fadeInUp}
                    className="pb-[48px] border-b border-white/5"
                >
                    <h1 className="font-serif text-[#F5F5F7] text-4xl md:text-6xl mb-4 leading-tight">
                        Privacy Policy
                    </h1>
                    <p className="text-[#6B7280] text-sm font-light uppercase tracking-wider">
                        Last updated: March 2026
                    </p>
                </motion.section>

                {/* SECTION 2 — INTRODUCTION */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="py-[48px] border-b border-white/5"
                >
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>AURSA respects your privacy.</p>
                        <p>This Privacy Policy explains what information we collect and how it is used when you use the AURSA website and application.</p>
                    </div>
                </motion.section>

                {/* SECTION 3 — INFORMATION WE COLLECT */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="py-[48px] border-b border-white/5"
                >
                    <h2 className="font-serif text-[#F5F5F7] text-2xl md:text-4xl mb-6 leading-tight">
                        Information We Collect
                    </h2>
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>When you use AURSA, we may collect limited information necessary for the product to function.</p>
                        <p>This includes:</p>
                        <ul className="list-disc pl-6 space-y-2 text-[#F5F5F7] font-medium">
                            <li><span className="text-[#A1A1AA] font-light">Email address when signing in with Google authentication</span></li>
                            <li><span className="text-[#A1A1AA] font-light">Outfit analysis results generated by the AI system</span></li>
                            <li><span className="text-[#A1A1AA] font-light">Basic product usage analytics (such as clicks and feature usage)</span></li>
                        </ul>
                    </div>
                </motion.section>

                {/* SECTION 4 — IMAGE PROCESSING */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="py-[48px] border-b border-white/5"
                >
                    <h2 className="font-serif text-[#F5F5F7] text-2xl md:text-4xl mb-6 leading-tight">
                        Outfit Image Processing
                    </h2>
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>When you upload an outfit photo, AURSA analyzes the image using AI to evaluate visual characteristics such as color harmony, contrast, layering, and balance.</p>
                        <p className="text-[#F5F5F7] font-medium mt-6">Important:</p>
                        <p>AURSA does <strong>not store uploaded images</strong>.</p>
                        <p>Images are processed only to generate visual analysis results, and only the resulting style metadata (analysis statistics) may be retained to improve the user experience.</p>
                    </div>
                </motion.section>

                {/* SECTION 5 — ANALYTICS */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="py-[48px] border-b border-white/5"
                >
                    <h2 className="font-serif text-[#F5F5F7] text-2xl md:text-4xl mb-6 leading-tight">
                        Product Analytics
                    </h2>
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>AURSA uses analytics tools to understand how users interact with the product.</p>
                        <p>This may include information such as:</p>
                        <ul className="list-disc pl-6 space-y-2 text-[#F5F5F7] font-medium">
                            <li><span className="text-[#A1A1AA] font-light">clicks</span></li>
                            <li><span className="text-[#A1A1AA] font-light">feature usage</span></li>
                            <li><span className="text-[#A1A1AA] font-light">general product interaction</span></li>
                        </ul>
                        <p>This data helps improve the experience and performance of AURSA.</p>
                    </div>
                </motion.section>

                {/* SECTION 6 — THIRD-PARTY SERVICES */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="py-[48px] border-b border-white/5"
                >
                    <h2 className="font-serif text-[#F5F5F7] text-2xl md:text-4xl mb-6 leading-tight">
                        Third-Party Services
                    </h2>
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>AURSA may use trusted services to operate the product, including:</p>
                        <ul className="list-disc pl-6 space-y-2 text-[#F5F5F7] font-medium">
                            <li><span className="text-[#A1A1AA] font-light">Google authentication for secure login</span></li>
                            <li><span className="text-[#A1A1AA] font-light">Analytics tools used to improve product experience</span></li>
                        </ul>
                        <p>These services may collect limited technical information necessary for functionality.</p>
                    </div>
                </motion.section>

                {/* SECTION 7 — DATA SECURITY */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="py-[48px] border-b border-white/5"
                >
                    <h2 className="font-serif text-[#F5F5F7] text-2xl md:text-4xl mb-6 leading-tight">
                        Data Security
                    </h2>
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>We take reasonable measures to protect user data and prevent unauthorized access.</p>
                        <p>However, no digital system can guarantee complete security.</p>
                    </div>
                </motion.section>

                {/* SECTION 8 — CONTACT */}
                <motion.section 
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: "-50px" }}
                    variants={fadeInUp}
                    className="pt-[48px]"
                >
                    <h2 className="font-serif text-[#F5F5F7] text-2xl md:text-4xl mb-6 leading-tight">
                        Contact
                    </h2>
                    <div className="space-y-[16px] text-[#A1A1AA] text-lg font-light leading-relaxed">
                        <p>If you have any questions about this Privacy Policy, please contact us at:</p>
                        <a 
                            href="mailto:aursa.app@gmail.com"
                            className="inline-block text-[#F5F5F7] hover:text-[#D88A3D] transition-colors duration-200 font-medium"
                        >
                            aursa.app@gmail.com
                        </a>
                    </div>
                </motion.section>

            </div>
        </div>
    );
};

export default PrivacyPolicyPage;
